# Generated by Django 3.2.9 on 2021-11-15 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.PositiveIntegerField(verbose_name='ID User')),
                ('name', models.CharField(max_length=64, verbose_name='Name of bill')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Balance')),
            ],
        ),
    ]
