# Generated by Django 3.2.9 on 2021-11-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='start_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=9, verbose_name='Start balance'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Current balance'),
        ),
    ]
