# Generated by Django 3.2.9 on 2021-11-15 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID User')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Description of operation')),
                ('date', models.DateField(auto_now_add=True)),
                ('isIncome', models.BooleanField(default=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Value of operation')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operations.categorytouser', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='OperationToBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='bills.bill', verbose_name='Bill of operation')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_bank', to='operations.operation', verbose_name='Operation')),
            ],
        ),
    ]
