# Generated by Django 3.2.9 on 2021-11-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytouser',
            name='isIncome',
            field=models.BooleanField(default=True, verbose_name='Is income type of category'),
        ),
    ]
