# Generated by Django 3.2.9 on 2021-11-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_categorytouser_isincome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtobill',
            name='operation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_bill', to='operations.operation', verbose_name='Operation'),
        ),
    ]
