# Generated by Django 3.2.9 on 2021-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_operationtobill_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
