# Generated by Django 3.2.9 on 2021-11-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_operationtobill_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operations.categorytouser', verbose_name='Category'),
        ),
    ]
