# Generated by Django 3.2.9 on 2022-01-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_operation_category'),
        ('operations', '0004_operation_currency'),
    ]

    operations = [
    ]
