# Generated by Django 3.2.9 on 2022-01-12 10:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_bill_currency'),
        ('operations', '0005_merge_20220112_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operations.categorytouser', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='TransferOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Value of operation')),
                ('from_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='bills.bill')),
                ('to_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='bills.bill')),
            ],
        ),
    ]
