# Generated by Django 3.2.9 on 2022-01-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20220112_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferoperation',
            name='value',
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='value_from',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Value of transfer for currency from bill'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='value_to',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Value of transfer for currency to bill'),
        ),
    ]
